SDK-391: temporarily ban a peer if we cannot deserialize a message
HorizenOfficial/Sparkz pull request #26
Opened 2022-09-19 14:42 UTC by paologalligit

2022-09-23 07:43 UTC, i-Alex approved these changes

2022-09-27 08:45 UTC, i-Alex requested changes
Suggest to close this PR and do all the changes in PR https://github.com/HorizenOfficial/Sparkz/pull/24

2022-09-27 08:45 UTC, i-Alex commented on src/main/scala/sparkz/core/network/PeerConnectionHandler.scala
> +                networkControllerRef ! PenalizePeer(connectionId.remoteAddress, PenaltyType.MisbehaviorPenalty)
since we don't ban the peer now, and don't disconnect we need to cleanup somehow `chunksBuffer` to avoid being blocked by the same error message.

2022-09-27 10:04 UTC, paologalligit commented
Closing; the changes will be integrated into [PR #24](https://github.com/HorizenOfficial/Sparkz/pull/24)

2022-09-27 10:04 UTC, closed without merging