SDK-1032 - SyncTracker.statuses maps fixes
HorizenOfficial/Sparkz pull request #57
Opened 2023-06-15 15:56 UTC by davehorizen

Details in Jira task [SDK-1032](https://horizenlabs.atlassian.net/browse/SDK-1032)

2023-06-20 14:19 UTC, saratnt requested changes

2023-06-20 14:19 UTC, saratnt commented on src/main/scala/sparkz/core/network/NetworkController.scala
> +      }
`case false` is missing here, so in case of address != peerAddress a scala.MatchError will be thrown.

2023-06-30 09:16 UTC, paologalligit commented on src/main/scala/sparkz/core/network/NetworkController.scala
> +      case (address, connectedPeer) => address == peerAddress match {
I think this can be made simpler by including the equality as a case condition:
```
 case (address, connectedPeer) if address == peerAddress =>
          connectedPeer.handlerRef ! CloseConnection
          context.system.eventStream.publish(DisconnectedPeer(peerAddress))
          true // exclude the entry from the filtered map
```

2023-07-04 07:30 UTC, davehorizen commented on src/main/scala/sparkz/core/network/NetworkController.scala
> +      }
`false` case added

2023-07-04 07:30 UTC, davehorizen commented on src/main/scala/sparkz/core/network/NetworkController.scala
> +      case (address, connectedPeer) => address == peerAddress match {
agree, method refactored

2023-07-04 07:44 UTC, saratnt approved these changes

2023-07-04 07:56 UTC, i-skrypnyk approved these changes

2023-07-04 08:27 UTC, paologalligit approved these changes

2023-07-18 07:50 UTC, merged